import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';

const RequestSchema = z.object({
  code: z.string().min(1, 'Code is required'),
  appName: z.string().min(1, 'App name is required'),
  packageName: z.string().optional(),
  description: z.string().optional(),
});

// Generate PWA manifest
function generateManifest(appName: string, description?: string) {
  return {
    name: appName,
    short_name: appName.substring(0, 12),
    description: description || `${appName} - Generated by CodeCraft`,
    start_url: "/",
    display: "standalone",
    background_color: "#ffffff",
    theme_color: "#3b82f6",
    orientation: "portrait-primary",
    icons: [
      {
        src: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTkyIiBoZWlnaHQ9IjE5MiIgdmlld0JveD0iMCAwIDE5MiAxOTIiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxOTIiIGhlaWdodD0iMTkyIiByeD0iMjQiIGZpbGw9IiMzYjgyZjYiLz4KPHN2ZyB4PSI0OCIgeT0iNDgiIHdpZHRoPSI5NiIgaGVpZ2h0PSI5NiIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBzdHJva2U9IndoaXRlIiBzdHJva2Utd2lkdGg9IjIiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+CjxwYXRoIGQ9Im0xOCA2LTEyIDEyIi8+CjxwYXRoIGQ9Im02IDYgMTIgMTIiLz4KPC9zdmc+Cjwvc3ZnPgo=",
        sizes: "192x192",
        type: "image/svg+xml"
      },
      {
        src: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTEyIiBoZWlnaHQ9IjUxMiIgdmlld0JveD0iMCAwIDUxMiA1MTIiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSI1MTIiIGhlaWdodD0iNTEyIiByeD0iNjQiIGZpbGw9IiMzYjgyZjYiLz4KPHN2ZyB4PSIxMjgiIHk9IjEyOCIgd2lkdGg9IjI1NiIgaGVpZ2h0PSIyNTYiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgc3Ryb2tlPSJ3aGl0ZSIgc3Ryb2tlLXdpZHRoPSIyIiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiPgo8cGF0aCBkPSJtMTggNi0xMiAxMiIvPgo8cGF0aCBkPSJtNiA2IDEyIDEyIi8+Cjwvc3ZnPgo8L3N2Zz4K",
        sizes: "512x512",
        type: "image/svg+xml"
      }
    ]
  };
}

// Generate service worker
function generateServiceWorker() {
  return `
const CACHE_NAME = 'codecraft-app-v1';
const urlsToCache = [
  '/',
  '/static/js/bundle.js',
  '/static/css/main.css',
  'https://cdn.tailwindcss.com',
  'https://unpkg.com/react@18/umd/react.production.min.js',
  'https://unpkg.com/react-dom@18/umd/react-dom.production.min.js',
  'https://unpkg.com/lucide-react@latest/dist/umd/lucide-react.js'
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(urlsToCache))
  );
});

self.addEventListener('fetch', (event) => {
  event.respondWith(
    caches.match(event.request)
      .then((response) => {
        if (response) {
          return response;
        }
        return fetch(event.request);
      }
    )
  );
});
`;
}

// Generate complete PWA HTML
function generatePWAHtml(code: string, appName: string, description?: string) {
  // Clean and prepare the code
  let cleanCode = code
    .replace(/^import.*$/gm, '') // Remove all import statements
    .replace(/^export\s+default\s+/gm, 'const App = ') // Replace export default with const App =
    .trim();

  // If the code doesn't have a proper App component declaration, wrap it
  if (!cleanCode.includes('const App =') && !cleanCode.includes('function App')) {
    cleanCode = `const App = () => {\n${cleanCode}\n};`;
  }

  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="${description || `${appName} - Generated by CodeCraft`}">
    <meta name="theme-color" content="#3b82f6">
    <title>${appName}</title>
    
    <!-- PWA Manifest -->
    <link rel="manifest" href="/manifest.json">
    
    <!-- iOS PWA Support -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <meta name="apple-mobile-web-app-title" content="${appName}">
    <link rel="apple-touch-icon" href="data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTkyIiBoZWlnaHQ9IjE5MiIgdmlld0JveD0iMCAwIDE5MiAxOTIiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxOTIiIGhlaWdodD0iMTkyIiByeD0iMjQiIGZpbGw9IiMzYjgyZjYiLz4KPHN2ZyB4PSI0OCIgeT0iNDgiIHdpZHRoPSI5NiIgaGVpZ2h0PSI5NiIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBzdHJva2U9IndoaXRlIiBzdHJva2Utd2lkdGg9IjIiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+CjxwYXRoIGQ9Im0xOCA2LTEyIDEyIi8+CjxwYXRoIGQ9Im02IDYgMTIgMTIiLz4KPC9zdmc+Cjwvc3ZnPgo=">
    
    <!-- External Dependencies -->
    <script src="https://cdn.tailwindcss.com"></script>
    <script crossorigin src="https://unpkg.com/react@18/umd/react.production.min.js"></script>
    <script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></script>
    <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
    <script src="https://unpkg.com/lucide-react@latest/dist/umd/lucide-react.js"></script>
    
    <style>
        body {
            margin: 0;
            padding: 0;
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif;
            -webkit-font-smoothing: antialiased;
            -moz-osx-font-smoothing: grayscale;
        }
        #root {
            width: 100%;
            min-height: 100vh;
        }
        /* PWA Install Prompt Styles */
        .install-prompt {
            position: fixed;
            bottom: 20px;
            left: 20px;
            right: 20px;
            background: #3b82f6;
            color: white;
            padding: 16px;
            border-radius: 8px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.15);
            display: none;
            z-index: 1000;
        }
        .install-prompt.show {
            display: block;
        }
        .install-prompt button {
            background: white;
            color: #3b82f6;
            border: none;
            padding: 8px 16px;
            border-radius: 4px;
            margin-left: 12px;
            cursor: pointer;
            font-weight: 600;
        }
        .install-prompt .close {
            background: transparent;
            color: white;
            border: 1px solid white;
        }
    </style>
</head>
<body>
    <div id="root"></div>
    
    <!-- PWA Install Prompt -->
    <div id="installPrompt" class="install-prompt">
        <span>Install ${appName} for a better experience!</span>
        <button id="installBtn">Install</button>
        <button id="dismissBtn" class="close">Dismiss</button>
    </div>
    
    <script type="text/babel">
        const { useState, useEffect, useRef, useCallback, useMemo, useReducer, useContext, createContext } = React;
        const { createRoot } = ReactDOM;
        
        // Make all Lucide React icons available globally
        const LucideIcons = LucideReact;
        const {
            ArrowRight, ArrowLeft, ArrowUp, ArrowDown, Plus, Minus, X, Check, Edit, Trash, Save, Search, Filter, Settings, User, Home, Menu, ChevronDown, ChevronUp, ChevronLeft, ChevronRight, Star, Heart, Share, Download, Upload, Play, Pause, Stop, Volume2, VolumeX, Calendar, Clock, Mail, Phone, MapPin, Globe, Camera, Image, Video, Music, File, Folder, Link, Lock, Unlock, Eye, EyeOff, Bell, BellOff, Bookmark, BookmarkCheck, Flag, Tag, Zap, Wifi, WifiOff, Battery, BatteryLow, Bluetooth, Cpu, HardDrive, Monitor, Smartphone, Tablet, Laptop, Server, Database, Cloud, CloudOff, Shield, ShieldCheck, AlertTriangle, AlertCircle, Info, HelpCircle, MessageCircle, MessageSquare, Send, Paperclip, Smile, ThumbsUp, ThumbsDown, TrendingUp, TrendingDown, BarChart, PieChart, Activity, Target, Award, Gift, ShoppingCart, ShoppingBag, CreditCard, DollarSign, Percent, Calculator, Ruler, Scissors, Palette, Brush, Pen, PenTool, Type, AlignLeft, AlignCenter, AlignRight, Bold, Italic, Underline, List, Grid, Layers, Move, RotateCw, RotateCcw, ZoomIn, ZoomOut, Maximize, Minimize, Copy, Cut, Paste, Undo, Redo, RefreshCw, MoreHorizontal, MoreVertical, ExternalLink, Github, Twitter, Facebook, Instagram, Linkedin, Youtube, Twitch, Discord, Slack, Figma, Chrome, Firefox, Safari, Edge, Code, Terminal, Package, Npm, Yarn, Git, Branch, Merge, PullRequest, Issue, Commit, Tag as GitTag, Release, Workflow, Action, Build, Deploy, Test, Bug, Feature, Enhancement, Documentation, Security, Performance, Accessibility, Mobile, Desktop, Tablet as TabletIcon, Watch, Tv, Gamepad2, Headphones, Mic, MicOff, Speaker, Radio, Podcast, Rss, Bookmark as BookmarkIcon, History, Archive, Trash2, Delete, Remove, Add, Create, New, Open, Close, Minimize2, Maximize2, FullScreen, ExitFullScreen, Expand, Collapse, Sidebar, Layout, Grid3x3, Columns, Rows, Table, List as ListIcon, Card, Kanban, Timeline, Gantt, Chart, Graph, Analytics, Report, Dashboard, Widget, Component, Element, Block, Section, Header, Footer, Navigation, Breadcrumb, Pagination, Tab, Modal, Dialog, Popup, Tooltip, Dropdown, Select, Input, Textarea, Button, Checkbox, Radio, Switch, Slider, Progress, Loading, Spinner, Skeleton, Avatar, Badge, Chip, Tag as TagIcon, Label, Caption, Title, Heading, Paragraph, Text, Quote, Code2, Pre, Syntax, Highlight, Comment, Note, Warning, Error, Success, Info as InfoIcon, Question, Help, Support, Contact, About, Privacy, Terms, Legal, License, Copyright, Trademark, Patent, Brand, Logo, Icon, Image as ImageIcon, Photo, Picture, Gallery, Slideshow, Carousel, Slider as SliderIcon, Banner, Hero, Feature, Testimonial, Review, Rating, Score, Rank, Level, Progress as ProgressIcon, Status, State, Flag as FlagIcon, Marker, Pin, Location, Map, Direction, Route, Path, Journey, Trip, Travel, Transport, Car, Bus, Train, Plane, Ship, Bike, Walk, Run, Sport, Game, Toy, Gift as GiftIcon, Present, Surprise, Celebration, Party, Event, Meeting, Conference, Webinar, Workshop, Course, Lesson, Tutorial, Guide, Manual, Book, Library, Archive as ArchiveIcon, Collection, Album, Playlist, Track, Song, Artist, Band, Concert, Festival, Show, Movie, Film, Video as VideoIcon, Stream, Live, Record, Broadcast, Podcast as PodcastIcon, Radio as RadioIcon, News, Article, Blog, Post, Story, Content, Media, Social, Network, Community, Group, Team, Organization, Company, Business, Enterprise, Startup, Venture, Investment, Finance, Money, Currency, Payment, Transaction, Invoice, Receipt, Bill, Tax, Budget, Expense, Income, Profit, Loss, Revenue, Sales, Marketing, Advertising, Campaign, Promotion, Discount, Coupon, Offer, Deal, Price, Cost, Value, Worth, Quality, Quantity, Amount, Number, Count, Sum, Total, Average, Median, Mode, Range, Min, Max, Limit, Threshold, Boundary, Border, Edge, Corner, Center, Middle, Side, Top, Bottom, Left, Right, Front, Back, Inside, Outside, Above, Below, Before, After, First, Last, Previous, Next, Forward, Backward, Up, Down, North, South, East, West, Northeast, Northwest, Southeast, Southwest
        } = LucideReact;

        try {
            ${cleanCode}
            
            const root = createRoot(document.getElementById('root'));
            root.render(React.createElement(App));
        } catch (error) {
            console.error('Error rendering app:', error);
            document.getElementById('root').innerHTML = '<div style="padding: 20px; color: red; font-family: monospace;">Error: ' + error.message + '</div>';
        }
    </script>
    
    <!-- PWA Installation Script -->
    <script>
        let deferredPrompt;
        const installPrompt = document.getElementById('installPrompt');
        const installBtn = document.getElementById('installBtn');
        const dismissBtn = document.getElementById('dismissBtn');

        window.addEventListener('beforeinstallprompt', (e) => {
            e.preventDefault();
            deferredPrompt = e;
            installPrompt.classList.add('show');
        });

        installBtn.addEventListener('click', async () => {
            if (deferredPrompt) {
                deferredPrompt.prompt();
                const { outcome } = await deferredPrompt.userChoice;
                deferredPrompt = null;
                installPrompt.classList.remove('show');
            }
        });

        dismissBtn.addEventListener('click', () => {
            installPrompt.classList.remove('show');
        });

        // Register service worker
        if ('serviceWorker' in navigator) {
            window.addEventListener('load', () => {
                navigator.serviceWorker.register('/sw.js')
                    .then((registration) => {
                        console.log('SW registered: ', registration);
                    })
                    .catch((registrationError) => {
                        console.log('SW registration failed: ', registrationError);
                    });
            });
        }
    </script>
</body>
</html>`;
}

export async function POST(req: NextRequest) {
  try {
    const json = await req.json();
    const result = RequestSchema.safeParse(json);
    
    if (!result.success) {
      return NextResponse.json(
        { error: result.error.message },
        { status: 422 }
      );
    }

    const { code, appName, packageName, description } = result.data;

    // Generate PWA files
    const manifest = generateManifest(appName, description);
    const serviceWorker = generateServiceWorker();
    const htmlContent = generatePWAHtml(code, appName, description);

    // Prepare files for PWABuilder
    const pwaFiles = {
      'index.html': htmlContent,
      'manifest.json': JSON.stringify(manifest, null, 2),
      'sw.js': serviceWorker,
    };

    // Use PWABuilder API to generate APK
    const pwaBuilderResponse = await fetch('https://pwabuilder-apk-web.azurewebsites.net/generateApk', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name: appName,
        packageId: packageName || `com.codecraft.${appName.toLowerCase().replace(/[^a-z0-9]/g, '')}`,
        url: 'data:text/html;base64,' + Buffer.from(htmlContent).toString('base64'),
        manifest: manifest,
        options: {
          packageId: packageName || `com.codecraft.${appName.toLowerCase().replace(/[^a-z0-9]/g, '')}`,
          name: appName,
          launcherName: appName,
          themeColor: '#3b82f6',
          navigationColor: '#3b82f6',
          backgroundColor: '#ffffff',
          startUrl: '/',
          iconUrl: manifest.icons[0].src,
          maskableIconUrl: manifest.icons[0].src,
          shortcuts: [],
          signing: {
            file: null,
            alias: null,
            fullName: 'CodeCraft User',
            organization: 'CodeCraft',
            organizationalUnit: 'Development',
            countryCode: 'US'
          }
        }
      }),
    });

    if (!pwaBuilderResponse.ok) {
      // Fallback: Return PWA files for manual APK generation
      return NextResponse.json({
        success: true,
        type: 'pwa_files',
        message: 'PWA files generated. You can use these with Android Studio or Capacitor to create an APK.',
        files: pwaFiles,
        instructions: [
          '1. Download and extract the PWA files',
          '2. Use Capacitor CLI: npx @capacitor/cli create',
          '3. Add Android platform: npx cap add android',
          '4. Copy files to www/ directory',
          '5. Build: npx cap build android',
          '6. Open in Android Studio: npx cap open android'
        ]
      });
    }

    const apkData = await pwaBuilderResponse.json();

    return NextResponse.json({
      success: true,
      type: 'apk_ready',
      downloadUrl: apkData.downloadUrl || apkData.url,
      buildId: apkData.buildId,
      message: 'APK generated successfully!',
      files: pwaFiles // Include PWA files as backup
    });

  } catch (error: any) {
    console.error('Error converting to APK:', error);
    
    // Return PWA files as fallback
    const { code, appName, description } = await req.json();
    const manifest = generateManifest(appName, description);
    const serviceWorker = generateServiceWorker();
    const htmlContent = generatePWAHtml(code, appName, description);

    return NextResponse.json({
      success: true,
      type: 'pwa_files',
      message: 'APK service unavailable. PWA files generated for manual conversion.',
      files: {
        'index.html': htmlContent,
        'manifest.json': JSON.stringify(manifest, null, 2),
        'sw.js': serviceWorker,
      },
      error: error.message
    });
  }
}

export const runtime = 'edge';